services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d 
    networks:
      - app-network

  messageservice:
    build:
      context: ./MessageService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
    ports:
      - "${SERVER_PORT}:80" 
    depends_on:
      - db
    networks:
      - app-network

  messagesenderclient:
    build:
      context: ./MessageSenderClient
      dockerfile: Dockerfile
    depends_on:
      - messageservice
    environment:
      - SERVER_URL=http://messageservice:80/api/messages
    networks:
      - app-network

  messagereceiverclient:
    build:
      context: ./MessageReceiverClient
      dockerfile: Dockerfile
    depends_on:
      - messageservice
    environment:
      - SERVER_WEBSOCKET_URL=${SERVER_WEBSOCKET_URL}
    networks:
      - app-network

  messagehistoryclient:
    build:
      context: ./MessageHistoryClient
      dockerfile: Dockerfile
    depends_on:
      - messageservice
    environment:
      - SERVER_URL=http://messageservice:80/api/messages
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
